name: DeployToGitHubPages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.103

      - name: Publish app
        run: dotnet publish -c Release -o release

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: release/wwwroot/index.html
          base_href: /BlazorCarCare/

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
